# Generated by cmd/update-formula; do not edit. Change tools/<name>.json or the generator.
class CodeRules < Formula
  desc "The package manager for engineering best practices"
  homepage "https://code-rules.fabricahq.com"
  license "MIT"

  livecheck do
    url :stable
    regex(/^v(\d+\.\d+\.\d+)$/i)
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.1.0/code-rules_0.1.0_darwin_arm64.tar.gz"
      sha256 "38130844b18c2ab8e04007b89c59afa5be43b9d816a2b6156e2b2452a574f985"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.1.0/code-rules_0.1.0_darwin_amd64.tar.gz"
      sha256 "884e8df6474c5ba8d0f434546ee772cbbd96ec47a34c5648d87e08717ec81f81"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.1.0/code-rules_0.1.0_linux_arm64.tar.gz"
      sha256 "e92762a7d95dcfd840f0a9e7726f13dcb43df299eaeb2a7684285a1baf92ca33"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.1.0/code-rules_0.1.0_linux_amd64.tar.gz"
      sha256 "d918901817b51ff1ed7c9ec99d961eb5eb8c429f60fb76b8dc2a5641fcca0267"
    end
  end

  def install
    bin.install "code-rules"
    prefix.install "LICENSE.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/code-rules --version")
    system bin/"code-rules", "--help"
  end
end
