# Generated by cmd/update-formula; do not edit. Change tools/<name>.json or the generator.
class CodeRules < Formula
  desc "The package manager for engineering best practices"
  homepage "https://code-rules.fabricahq.com"
  license "MIT"

  livecheck do
    url :stable
    regex(/^v(\d+\.\d+\.\d+)$/i)
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.2.0/code-rules_0.2.0_darwin_arm64.tar.gz"
      sha256 "78dd8672a5f495424fabeacc6eb989504041b7f29a6b8e01d0022308a0998142"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.2.0/code-rules_0.2.0_darwin_amd64.tar.gz"
      sha256 "a4c366b93dd5d7d8d1c4a02487a6e10e57590a1249d075deda2c48f6f42a6036"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.2.0/code-rules_0.2.0_linux_arm64.tar.gz"
      sha256 "a38be1da2b6d8d9bd8938136d1a397fdc8ced81c236b248ba7c495e92c9d6882"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.2.0/code-rules_0.2.0_linux_amd64.tar.gz"
      sha256 "412783548d3b2cb90df17d533b9ca96531dec428931d3a4e27a78a5741de4190"
    end
  end

  def install
    bin.install "code-rules"
    prefix.install "LICENSE.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/code-rules --version")
    system bin/"code-rules", "--help"
  end
end
