# Generated by cmd/update-formula; do not edit. Change tools/<name>.json or the generator.
class CodeRules < Formula
  desc "The package manager for engineering best practices"
  homepage "https://code-rules.fabricahq.com"
  license "MIT"

  livecheck do
    url :stable
    regex(/^v(\d+\.\d+\.\d+)$/i)
    strategy :github_latest
  end

  on_macos do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.3.0/code-rules_0.3.0_darwin_arm64.tar.gz"
      sha256 "47722b4a8e51b85695b66eb71a9c0aea514421c285e57e5c118658642d63e5db"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.3.0/code-rules_0.3.0_darwin_amd64.tar.gz"
      sha256 "7d3727ce450b47b6d2349f82c7c24389a82556f0e3abefe497fdae4632a0b99e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.3.0/code-rules_0.3.0_linux_arm64.tar.gz"
      sha256 "b37e73de22615de5b3f1844b018091f835e377db42354876c67f13b7a7b8247b"
    end

    on_intel do
      url "https://github.com/fabricahq/code-rules/releases/download/v0.3.0/code-rules_0.3.0_linux_amd64.tar.gz"
      sha256 "7d78b778dfbd4d5d50b03766d0ae88995c7233a5584e845a2c777b2f31f1a764"
    end
  end

  def install
    bin.install "code-rules"
    prefix.install "LICENSE.md"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/code-rules --version")
    system bin/"code-rules", "--help"
  end
end
